#!/bin/bash
#logger "*** brighness script started***"

br_name_max=/sys/class/backlight/intel_backlight/max_brightness
[[ -e "$br_name_max" ]] || exit 0
br_name=/sys/class/backlight/intel_backlight/brightness
[[ -e "$br_name" ]] || exit 0

br_max=$(cat "$br_name_max")
br=$(cat "$br_name")

br_powersave=$((60*br_max/100)) # 60% from full brightness
[[ "$br" -lt "$br_powersave" ]] && exit 0

case $1 in
  true)
    logger "Enable screen power saving"
    #echo 9 > /sys/class/backlight/acpi_video0/brightness
    echo "$br_powersave" > /sys/class/backlight/intel_backlight/brightness
    ;;
  false)
    logger "Disable screen power saving"
    #echo 15 > /sys/class/backlight/acpi_video0/brightness
    echo "$br_max" > /sys/class/backlight/intel_backlight/brightness
    ;;
esac
