#!/bin/bash

case $1 in
  true)
    logger "Use powersave cpu governer when on the battery"
    echo powersave | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
    ;;
  false)
    logger "Use ondemand cpu governer when on AC"
    echo performance | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
    ;;
esac
exit 0

